(autoload 'js3-mode "js3")
(add-to-list 'auto-mode-alist '("\\.js$" . js3-mode))
(add-to-list 'auto-mode-alist '("\\.json$" . json-mode))
;; (require 'nodejs-repl)
;; (defalias 'repl 'nodejs-repl)
(provide 'init-js)
