(require 'multiple-cursors)
(global-set-key (kbd "C-c .") 'mc/mark-next-like-this)
(global-set-key (kbd "C-c ,") 'mc/mark-previous-like-this)
(global-set-key (kbd "C-c >") 'mc/skip-to-next-like-this)
(global-set-key (kbd "C-c <") 'mc/skip-to-previous-like-this)
(provide 'init-multiple-cursors)
