(require 'helm-config)
(require 'helm-mode)
(require 'helm-match-plugin)
(require 'helm-buffers)
(require 'helm-files)
(require 'helm-locate)
(require 'helm-w3m)
(global-set-key (kbd "C-c h") 'helm-mini)
(helm-mode 1)
(provide 'init-helm)
